/**
 * Procedural product illustrations (original artwork generated by this script, no third-party images).
 * Each product gets a soft gradient backdrop and a simple flat illustration of its kind of object,
 * rendered from SVG to an 800×800 WebP with sharp.
 */
import sharp from "sharp";

export type Shape = "bottle" | "mug" | "jar" | "lantern" | "plant" | "notebook" | "towel" | "pan" | "blanket" | "candle" | "knife" | "box" | "pen" | "pot" | "tent" | "chair";

const shapes: Record<Shape, (c: string, a: string) => string> = {
  bottle: (c, a) => `<rect x="330" y="190" width="140" height="420" rx="60" fill="${c}"/><rect x="360" y="140" width="80" height="70" rx="14" fill="${a}"/><rect x="330" y="330" width="140" height="90" fill="${a}" opacity=".35"/>`,
  mug: (c, a) => `<rect x="270" y="280" width="220" height="250" rx="34" fill="${c}"/><path d="M490 330 h40 a50 50 0 0 1 0 140 h-40" fill="none" stroke="${c}" stroke-width="34"/><rect x="270" y="280" width="220" height="40" rx="18" fill="${a}" opacity=".5"/>`,
  jar: (c, a) => `<rect x="290" y="240" width="220" height="320" rx="50" fill="${c}"/><rect x="300" y="200" width="200" height="60" rx="16" fill="${a}"/><rect x="330" y="350" width="140" height="90" rx="12" fill="#fff" opacity=".7"/>`,
  lantern: (c, a) => `<rect x="320" y="250" width="160" height="260" rx="30" fill="${c}"/><rect x="345" y="280" width="110" height="200" rx="20" fill="#fff4c2"/><circle cx="400" cy="380" r="35" fill="${a}"/><path d="M340 250 q60 -110 120 0" fill="none" stroke="${c}" stroke-width="16"/><rect x="300" y="500" width="200" height="34" rx="12" fill="${c}"/>`,
  plant: (c, a) => `<path d="M330 430 h140 l-20 150 h-100 z" fill="${a}"/><path d="M400 430 C 300 380 290 270 330 210 C 380 260 400 330 400 430" fill="${c}"/><path d="M400 430 C 500 380 510 280 470 220 C 420 270 400 340 400 430" fill="${c}" opacity=".85"/><path d="M400 430 C 380 330 400 250 400 190" stroke="${c}" stroke-width="10" fill="none"/>`,
  notebook: (c, a) => `<rect x="280" y="200" width="250" height="360" rx="18" fill="${c}"/><rect x="280" y="200" width="36" height="360" fill="${a}"/><rect x="350" y="270" width="140" height="18" rx="9" fill="#fff" opacity=".7"/><rect x="350" y="310" width="100" height="14" rx="7" fill="#fff" opacity=".5"/><rect x="490" y="200" width="18" height="140" fill="${a}"/>`,
  towel: (c, a) => `<rect x="260" y="230" width="280" height="330" rx="20" fill="${c}"/><rect x="260" y="470" width="280" height="30" fill="${a}"/><rect x="260" y="290" width="280" height="12" fill="${a}" opacity=".6"/><rect x="240" y="210" width="320" height="34" rx="17" fill="${a}" opacity=".8"/>`,
  pan: (c, a) => `<circle cx="370" cy="400" r="150" fill="${c}"/><circle cx="370" cy="400" r="115" fill="${a}" opacity=".45"/><rect x="510" y="385" width="190" height="34" rx="17" fill="${c}"/>`,
  blanket: (c, a) => `<path d="M230 260 h340 v260 q-170 70 -340 0 z" fill="${c}"/><path d="M230 330 h340 M230 400 h340" stroke="${a}" stroke-width="18"/><path d="M290 260 v300 M510 260 v300" stroke="${a}" stroke-width="10" opacity=".6"/>`,
  candle: (c, a) => `<rect x="320" y="300" width="160" height="250" rx="22" fill="${c}"/><path d="M400 300 v-40" stroke="#333" stroke-width="6"/><path d="M400 200 q30 40 0 70 q-30 -30 0 -70" fill="#ffb347"/><rect x="320" y="380" width="160" height="60" fill="${a}" opacity=".5"/>`,
  knife: (c, a) => `<path d="M220 420 L560 300 q30 -5 10 25 L250 470 z" fill="#d9dee3"/><rect x="520" y="300" width="180" height="50" rx="22" transform="rotate(-20 520 300)" fill="${c}"/><circle cx="600" cy="300" r="7" fill="${a}"/>`,
  box: (c, a) => `<path d="M260 320 l140 -70 l140 70 v190 l-140 70 l-140 -70 z" fill="${c}"/><path d="M260 320 l140 70 l140 -70 M400 390 v190" stroke="${a}" stroke-width="10" fill="none"/>`,
  pen: (c, a) => `<rect x="250" y="370" width="320" height="56" rx="28" fill="${c}"/><path d="M570 370 l70 28 l-70 28 z" fill="${a}"/><rect x="290" y="355" width="120" height="16" rx="8" fill="${a}"/>`,
  pot: (c, a) => `<path d="M270 330 h260 l-30 230 h-200 z" fill="${c}"/><rect x="250" y="300" width="300" height="50" rx="14" fill="${a}"/><path d="M330 300 q70 -120 140 0" fill="#7fae74" />`,
  tent: (c, a) => `<path d="M400 210 L620 560 H180 Z" fill="${c}"/><path d="M400 210 L470 560 H330 Z" fill="${a}"/><path d="M180 560 H620" stroke="${a}" stroke-width="12"/>`,
  chair: (c, a) => `<rect x="300" y="380" width="220" height="40" rx="12" fill="${c}"/><rect x="300" y="220" width="40" height="200" rx="12" fill="${c}"/><path d="M310 420 l-20 160 M510 420 l20 160 M330 420 l20 160" stroke="${a}" stroke-width="16" stroke-linecap="round"/>`,
};

export function productSvg(shape: Shape, color: string, accent: string, bg: [string, string]): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800" width="800" height="800">
  <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${bg[0]}"/><stop offset="1" stop-color="${bg[1]}"/></linearGradient></defs>
  <rect width="800" height="800" fill="url(#g)"/>
  <ellipse cx="400" cy="610" rx="230" ry="26" fill="#000" opacity=".08"/>
  ${shapes[shape](color, accent)}
</svg>`;
}

export async function renderProductImage(file: string, shape: Shape, color: string, accent: string, bg: [string, string]) {
  await sharp(Buffer.from(productSvg(shape, color, accent, bg))).webp({ quality: 82 }).toFile(file);
}

export const CATEGORY_BG: Record<string, [string, string]> = {
  kitchen: ["#fdf3e7", "#f6dcc0"],
  outdoor: ["#e8f2ea", "#c9e0cf"],
  home: ["#f1eef8", "#d9d2ec"],
  bath: ["#e8f3f7", "#c8e2ec"],
  stationery: ["#fbf6e3", "#efe2b3"],
  garden: ["#eef5e4", "#d3e6bd"],
};
