/**
 * SEED DATA — a fictional catalog for "Fernwood Supply", written for this demo. Product names,
 * descriptions and prices are invented; images are generated procedurally (drizzle/product-art.ts).
 */
import type { Shape } from "./product-art";

export interface SeedProduct {
  name: string;
  category: "kitchen" | "outdoor" | "home" | "bath" | "stationery" | "garden";
  price: number;
  stock: number;
  featured?: boolean;
  shape: Shape;
  color: string;
  accent: string;
  attributes: Record<string, string>;
  description: string;
}

export const PRODUCTS: SeedProduct[] = [
  // Kitchen
  { name: "Trailhead Insulated Bottle 750 ml", category: "outdoor", price: 32, stock: 40, featured: true, shape: "bottle", color: "#2f6f5e", accent: "#1d4a3e", attributes: { Capacity: "750 ml", Material: "Double-wall stainless steel", Keeps: "Cold 24 h, hot 12 h" }, description: "A double-walled stainless steel bottle that keeps drinks cold for a full day on the trail or coffee hot through a long morning. The leak-proof lid clips onto a backpack strap." },
  { name: "Stoneware Morning Mug", category: "kitchen", price: 18, stock: 60, featured: true, shape: "mug", color: "#c8875a", accent: "#7a4a2b", attributes: { Capacity: "350 ml", Material: "Glazed stoneware", Care: "Dishwasher and microwave safe" }, description: "A hand-glazed stoneware mug with a generous handle, sized for a full cup of coffee or tea. Each glaze varies slightly, so no two mugs look exactly alike." },
  { name: "Cast Iron Skillet 10 in", category: "kitchen", price: 44, stock: 25, featured: true, shape: "pan", color: "#2b2b2b", accent: "#5a5a5a", attributes: { Diameter: "10 inch", Material: "Pre-seasoned cast iron", Use: "Stovetop, oven, campfire" }, description: "A pre-seasoned cast iron skillet for searing, baking cornbread or cooking over a campfire. It holds heat evenly and gets better with every use." },
  { name: "Glass Pantry Jar Set", category: "kitchen", price: 29, stock: 35, shape: "jar", color: "#cfe3e6", accent: "#8a6a4a", attributes: { Pieces: "3 jars (0.5, 1, 1.5 L)", Material: "Borosilicate glass, bamboo lids", Seal: "Silicone gasket" }, description: "Three airtight glass jars with bamboo lids for storing oats, pasta, beans or coffee beans. The silicone seal keeps dry goods fresh and pests out." },
  { name: "Olive Wood Chef's Knife", category: "kitchen", price: 68, stock: 15, shape: "knife", color: "#8b6a43", accent: "#3a2b1a", attributes: { Blade: "8 inch high-carbon stainless steel", Handle: "Olive wood", Care: "Hand wash only" }, description: "An 8-inch chef's knife with a high-carbon stainless steel blade and a warm olive wood handle. Balanced for everyday chopping, slicing and dicing." },
  { name: "Linen Tea Towel Pair", category: "kitchen", price: 16, stock: 80, shape: "towel", color: "#e7dccb", accent: "#b48a5a", attributes: { Pieces: "2 towels", Material: "100% washed linen", Size: "50 × 70 cm" }, description: "Two absorbent washed-linen tea towels that dry dishes without leaving lint and soften with every wash. A simple stripe keeps them looking tidy on the oven rail." },

  // Outdoor
  { name: "Ridgeline Camping Lantern", category: "outdoor", price: 38, stock: 30, featured: true, shape: "lantern", color: "#e2a03f", accent: "#7a4a12", attributes: { Brightness: "400 lumens", Battery: "USB-C rechargeable, up to 40 h", Rating: "IPX4 splash resistant" }, description: "A rechargeable LED lantern with warm and bright modes that lights up a whole tent or picnic table. It charges over USB-C and can top up a phone in an emergency." },
  { name: "Two-Person Backpacking Tent", category: "outdoor", price: 189, stock: 8, featured: true, shape: "tent", color: "#3d7a57", accent: "#255238", attributes: { Capacity: "2 people", Weight: "1.6 kg", Setup: "Freestanding, two doors" }, description: "A lightweight freestanding tent for two with a door on each side, so nobody climbs over anyone at night. It packs small enough to fit in a 40-litre backpack." },
  { name: "Packable Down Blanket", category: "outdoor", price: 99, stock: 12, shape: "blanket", color: "#5a7fb5", accent: "#2c4a7a", attributes: { Fill: "600-fill responsibly sourced down", Size: "130 × 180 cm", Packed: "Fits in included stuff sack" }, description: "A warm, lightweight down blanket for cold evenings at the campsite, on the porch or in the stands. It stuffs into its own sack for travel." },
  { name: "Folding Camp Chair", category: "outdoor", price: 54, stock: 20, shape: "chair", color: "#2f4f6f", accent: "#9aa9b8", attributes: { Weight: "1.1 kg", Capacity: "Holds up to 120 kg", Frame: "Aluminium" }, description: "A compact aluminium camp chair that folds into a small bag and sets up in seconds. Comfortable enough for a whole evening around the fire." },
  { name: "Enamel Camp Mug", category: "outdoor", price: 14, stock: 70, shape: "mug", color: "#f2f2f2", accent: "#1f3d5a", attributes: { Capacity: "400 ml", Material: "Enamel-coated steel", Use: "Safe on a camp stove" }, description: "A classic speckled enamel mug that can go straight onto a camp stove to heat water. Light, tough and easy to clip to a pack." },
  { name: "Waterproof Field Notebook", category: "stationery", price: 12, stock: 90, shape: "notebook", color: "#e0c341", accent: "#7a6512", attributes: { Pages: "48 sheets, grid", Paper: "Waterproof synthetic paper", Size: "Pocket, 9 × 14 cm" }, description: "A pocket notebook with waterproof pages that you can write on in the rain with a pencil. Made for fieldwork, hiking logs and gardening notes." },

  // Home
  { name: "Soy Candle — Cedar & Smoke", category: "home", price: 24, stock: 50, featured: true, shape: "candle", color: "#efe6d8", accent: "#5a4636", attributes: { Wax: "Soy wax, cotton wick", Burn: "About 45 hours", Scent: "Cedarwood, smoke, vetiver" }, description: "A hand-poured soy candle with notes of cedarwood and campfire smoke that makes any room feel like a cabin. Burns clean for about 45 hours." },
  { name: "Wool Throw Blanket", category: "home", price: 89, stock: 18, shape: "blanket", color: "#9b5a46", accent: "#e8d7c7", attributes: { Material: "100% merino wool", Size: "130 × 170 cm", Pattern: "Herringbone" }, description: "A soft merino wool throw in a herringbone weave for reading on the sofa or layering on the bed. Naturally warm and breathable." },
  { name: "Ceramic Table Lamp", category: "home", price: 79, stock: 10, shape: "lantern", color: "#6f8f87", accent: "#f3e9d2", attributes: { Base: "Glazed ceramic", Shade: "Linen", Bulb: "E26, LED bulb included" }, description: "A ceramic table lamp with a linen shade that casts a warm, even light for bedside tables and reading corners. LED bulb included." },
  { name: "Stackable Storage Box", category: "home", price: 22, stock: 45, shape: "box", color: "#c9b79c", accent: "#7a6650", attributes: { Material: "Recycled cardboard, linen wrap", Size: "30 × 25 × 20 cm", Load: "Stacks three high" }, description: "A sturdy linen-wrapped storage box for shelves, closets and kids' rooms. Boxes stack neatly and have cut-out handles for easy lifting." },
  { name: "Rattan Plant Stand", category: "home", price: 46, stock: 14, shape: "chair", color: "#b98b52", accent: "#6e4f2b", attributes: { Material: "Natural rattan", Height: "60 cm", Fits: "Pots up to 25 cm wide" }, description: "A hand-woven rattan stand that lifts a potted plant off the floor and adds natural texture to a room. Fits pots up to 25 cm across." },
  { name: "Glass Cloche Terrarium", category: "home", price: 34, stock: 0, shape: "jar", color: "#d6ebe3", accent: "#4b6b57", attributes: { Material: "Glass dome, oak base", Size: "20 cm tall", Use: "Succulents, moss, display" }, description: "A glass dome on an oak base for displaying a small moss garden, succulents or keepsakes. Currently sold out." },

  // Bath
  { name: "Waffle Bath Towel", category: "bath", price: 36, stock: 40, featured: true, shape: "towel", color: "#dfe7ec", accent: "#7c95a6", attributes: { Material: "100% Turkish cotton", Size: "75 × 140 cm", Weave: "Waffle" }, description: "A lightweight waffle-weave bath towel in Turkish cotton that dries quickly and gets softer with each wash. Great for small bathrooms and travel." },
  { name: "Cedar Bath Soak", category: "bath", price: 19, stock: 55, shape: "jar", color: "#e9e1d3", accent: "#6a7c5f", attributes: { Size: "400 g", Ingredients: "Epsom salt, sea salt, cedar oil", Use: "Two to three baths" }, description: "A mineral bath soak with Epsom and sea salts and a woodsy cedar scent for unwinding after a long hike or a long week." },
  { name: "Bamboo Bath Mat", category: "bath", price: 28, stock: 30, shape: "box", color: "#c8a76e", accent: "#8a6c3a", attributes: { Material: "Bamboo slats", Size: "50 × 80 cm", Feet: "Non-slip silicone" }, description: "A slatted bamboo mat that lets water drain and dries fast, with non-slip feet to keep it in place on tile floors." },
  { name: "Hand Soap — Lemon Verbena", category: "bath", price: 14, stock: 65, shape: "bottle", color: "#f1e38a", accent: "#7a8a2a", attributes: { Size: "350 ml", Base: "Plant-based, sulfate-free", Scent: "Lemon verbena" }, description: "A gentle plant-based hand soap with a fresh lemon verbena scent, in a refillable glass pump bottle." },
  { name: "Linen Shower Curtain", category: "bath", price: 58, stock: 16, shape: "towel", color: "#e3ddd2", accent: "#9a8f7c", attributes: { Material: "Stonewashed linen", Size: "180 × 180 cm", Note: "Use with a liner" }, description: "A stonewashed linen shower curtain with a relaxed, natural drape that makes a bathroom feel calm. Use it with a waterproof liner." },

  // Stationery
  { name: "Dot Grid Journal A5", category: "stationery", price: 22, stock: 75, featured: true, shape: "notebook", color: "#294a3b", accent: "#c9a85a", attributes: { Pages: "192 pages, numbered", Paper: "100 gsm, minimal ghosting", Binding: "Lay-flat" }, description: "A lay-flat A5 journal with numbered dot-grid pages for planning, sketching and bullet journaling. Thick paper keeps fountain pen ink from showing through." },
  { name: "Brass Fountain Pen", category: "stationery", price: 48, stock: 22, shape: "pen", color: "#c9a14a", accent: "#2b2b2b", attributes: { Body: "Solid brass", Nib: "Medium steel nib", Filling: "Standard ink cartridges" }, description: "A solid brass fountain pen that develops a warm patina with use. Writes smoothly with a medium steel nib and standard cartridges." },
  { name: "Recycled Paper Sticky Notes", category: "stationery", price: 7, stock: 120, shape: "notebook", color: "#f3d36b", accent: "#c79b2a", attributes: { Pack: "6 pads × 100 sheets", Paper: "100% recycled", Size: "76 × 76 mm" }, description: "A pack of sticky notes made from recycled paper in soft muted colors for reminders, labels and planning walls." },
  { name: "Desk Organizer Box", category: "stationery", price: 31, stock: 28, shape: "box", color: "#6b8aa3", accent: "#2f4d63", attributes: { Material: "Powder-coated steel", Compartments: "4", Size: "25 × 12 × 10 cm" }, description: "A steel desk organizer with four compartments for pens, scissors, notes and cables, keeping a work surface clear." },
  { name: "Mechanical Pencil Set", category: "stationery", price: 15, stock: 50, shape: "pen", color: "#3d3d3d", accent: "#d64e3a", attributes: { Pieces: "2 pencils (0.5 and 0.7 mm)", Extras: "Lead refills and erasers", Grip: "Knurled metal" }, description: "Two mechanical pencils with knurled metal grips for precise sketching and note-taking, with spare leads and erasers included." },

  // Garden
  { name: "Terracotta Herb Pot Trio", category: "garden", price: 26, stock: 40, featured: true, shape: "pot", color: "#c46a43", accent: "#9c4f2e", attributes: { Pieces: "3 pots (12 cm)", Material: "Unglazed terracotta", Drainage: "Hole and saucer" }, description: "Three terracotta pots with saucers, sized for growing basil, mint and parsley on a sunny windowsill. Unglazed clay lets roots breathe." },
  { name: "Ash Wood Garden Trowel", category: "garden", price: 21, stock: 35, shape: "knife", color: "#a07850", accent: "#5a6b6e", attributes: { Blade: "Stainless steel with depth marks", Handle: "Ash wood", Length: "30 cm" }, description: "A stainless steel trowel with depth markings for planting bulbs and seedlings, on a comfortable ash wood handle." },
  { name: "Self-Watering Planter", category: "garden", price: 39, stock: 24, shape: "pot", color: "#7f9a7a", accent: "#4f6b4c", attributes: { Reservoir: "1.5 L, lasts about 2 weeks", Material: "Recycled plastic", Diameter: "25 cm" }, description: "A planter with a hidden water reservoir that keeps houseplants watered for about two weeks — useful for travel or forgetful plant owners." },
  { name: "Seed Starter Kit", category: "garden", price: 27, stock: 30, shape: "box", color: "#8cb36a", accent: "#4f7a2f", attributes: { Contents: "Tray, 24 peat-free pots, dome", Seeds: "Tomato, basil, lettuce", Use: "Indoors, spring" }, description: "Everything needed to start vegetables and herbs indoors in spring: a tray, 24 peat-free pots, a humidity dome and three seed packets." },
  { name: "Copper Watering Can", category: "garden", price: 52, stock: 12, shape: "bottle", color: "#c07a43", accent: "#7a4a24", attributes: { Capacity: "1.5 L", Material: "Copper-plated steel", Spout: "Long, for indoor plants" }, description: "A slim copper-finished watering can with a long spout that reaches the base of houseplants without splashing leaves." },
  { name: "Gardening Gloves", category: "garden", price: 17, stock: 60, shape: "towel", color: "#7d8e5a", accent: "#4a5a2c", attributes: { Material: "Goatskin palms, cotton back", Sizes: "S, M, L", Feature: "Touchscreen fingertips" }, description: "Durable goatskin gardening gloves that protect against thorns while staying flexible, with fingertips that work on a phone screen." },
  { name: "Raised Bed Planter Box", category: "garden", price: 119, stock: 6, shape: "box", color: "#9a7650", accent: "#5e4428", attributes: { Material: "Untreated cedar", Size: "120 × 60 × 30 cm", Assembly: "Tool-free" }, description: "An untreated cedar raised bed for growing vegetables on a patio or small yard. Slots together without tools in about ten minutes." },
];
