import { expect, test, type Page } from "@playwright/test";

// README screenshots from a RUNNING app with a real AI provider (see playwright.screenshots.config.ts).
// Bookings shown are seed data; AI output in the images comes from real model calls.
const OUT = "docs/screenshots";

async function signIn(page: Page, role: "owner" | "customer", next: string) {
  await page.goto(`/sign-in?demo=${role}&next=${encodeURIComponent(next)}`);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.waitForURL((u) => u.pathname === new URL(next, "http://x").pathname);
  // Let the "Welcome back" toast disappear so it doesn't cover the page.
  await expect(page.locator("[data-sonner-toast]")).toHaveCount(0, { timeout: 10_000 });
}

test("capture README screenshots (real AI provider)", async ({ browser }) => {
  const page = await (await browser.newContext({ viewport: { width: 1360, height: 900 }, colorScheme: "light" })).newPage();
  await page.goto("/");
  await page.getByLabel("Describe what you'd like").fill("Deep tissue massage with Sam next week, mornings before 11am");
  await page.getByRole("button", { name: "Find times" }).click();
  await expect(page.getByText("Understood:")).toBeVisible({ timeout: 240_000 });
  await page.screenshot({ path: `${OUT}/home-assistant.png` });

  await signIn(page, "customer", "/book/swedish-massage");
  await expect(page.locator("[data-slot-start]").first()).toBeVisible();
  await page.screenshot({ path: `${OUT}/slot-picker.png`, fullPage: true });

  const owner = await (await browser.newContext({ viewport: { width: 1360, height: 900 }, colorScheme: "dark" })).newPage();
  await signIn(owner, "owner", "/dashboard");
  await expect(owner.getByRole("status").filter({ hasText: "Live" })).toBeVisible();
  await owner.screenshot({ path: `${OUT}/team-calendar-dark.png` });

  await owner.goto("/dashboard/digest");
  await owner.getByRole("button", { name: "Write this week's digest" }).click();
  await expect(owner.getByText(/AI-generated by/)).toBeVisible({ timeout: 300_000 });
  await owner.screenshot({ path: `${OUT}/weekly-digest-dark.png`, fullPage: true });

  const mobile = await (await browser.newContext({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true })).newPage();
  await mobile.goto("/book/signature-facial");
  await expect(mobile.locator("[data-slot-start]").first()).toBeVisible();
  await mobile.screenshot({ path: `${OUT}/booking-mobile.png` });
});
