import { expect, test, type Page } from "@playwright/test";

// README screenshots from a RUNNING app with a real AI provider (see playwright.screenshots.config.ts).
// Data is fictional seed data; AI output in the images comes from real model calls.
const OUT = "docs/screenshots";

async function signIn(page: Page, next: string) {
  await page.goto(`/sign-in?demo=analyst&next=${encodeURIComponent(next)}`);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.waitForURL((u) => u.pathname === new URL(next, "http://x").pathname);
  await expect(page.locator("[data-sonner-toast]")).toHaveCount(0, { timeout: 10_000 });
}

test("capture README screenshots (real AI provider)", async ({ browser }) => {
  const page = await (await browser.newContext({ viewport: { width: 1360, height: 900 }, colorScheme: "light" })).newPage();
  await page.goto("/");
  await page.screenshot({ path: `${OUT}/landing.png` });

  await signIn(page, "/ask");
  await page.getByLabel("Ask a question about the data").fill(process.env.SCREENSHOT_QUESTION ?? "Monthly revenue from completed orders");
  await page.getByRole("button", { name: "Ask", exact: true }).click();
  await expect(page.locator("pre code")).not.toHaveText("", { timeout: 300_000 });
  await expect(page.getByText(/rows ·/)).toBeVisible({ timeout: 300_000 });
  await page.waitForTimeout(500);
  await page.screenshot({ path: `${OUT}/ask-result.png`, fullPage: true });

  await page.getByRole("button", { name: "Summarize" }).click();
  await expect(page.getByText(/AI-generated by/)).toBeVisible({ timeout: 300_000 });
  await page.getByLabel("AI summary").scrollIntoViewIfNeeded();
  await page.screenshot({ path: `${OUT}/ask-summary.png` });

  const dark = await (await browser.newContext({ viewport: { width: 1360, height: 900 }, colorScheme: "dark" })).newPage();
  await signIn(dark, "/dashboards");
  await dark.getByRole("link", { name: /Sales overview \(example\)/ }).click();
  await expect(dark.locator("svg.recharts-surface").first()).toBeVisible();
  await dark.waitForTimeout(500);
  await dark.screenshot({ path: `${OUT}/dashboard-dark.png`, fullPage: true });

  await dark.goto("/ask");
  await dark.getByLabel("Ask a question about the data").fill("Delete all cancelled orders");
  await dark.getByRole("button", { name: "Ask", exact: true }).click();
  await expect(dark.getByText(/rows ·|attempts|couldn't|not allowed|can't be answered|No answer/i).first()).toBeVisible({ timeout: 300_000 });
  await dark.waitForTimeout(500);
  await dark.screenshot({ path: `${OUT}/unsafe-request-dark.png`, fullPage: true });

  const mobile = await (await browser.newContext({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true })).newPage();
  await mobile.goto("/");
  const href = await mobile.getByRole("link", { name: "See a shared dashboard" }).getAttribute("href");
  await mobile.goto(href!);
  await expect(mobile.locator("svg.recharts-surface").first()).toBeVisible();
  await mobile.screenshot({ path: `${OUT}/shared-mobile.png` });
});
