"use client";
import { AlertTriangle, Sparkles } from "lucide-react";
import { useState } from "react";
import { readTextStream } from "@portfolio/ai/stream";
import { AiUnavailable } from "@portfolio/ui/ai-unavailable";
import { Button } from "@portfolio/ui/button";
import { Spinner } from "@portfolio/ui/spinner";

interface Meta {
  unverified: string[];
  provider: string;
  model: string;
}

/** Model output is shown as plain text; stray markdown markers are removed rather than rendered. */
const plain = (t: string) => t.replace(/\*\*|__|^#{1,6}\s*/gm, "");

/** Streams the owner's weekly digest. The narrative is AI-written; numbers not found in the stats are flagged. */
export function DigestPanel({ aiAvailable }: { aiAvailable: boolean }) {
  const [text, setText] = useState("");
  const [meta, setMeta] = useState<Meta | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);

  async function generate() {
    setPending(true);
    setError(null);
    setText("");
    setMeta(null);
    try {
      const res = await fetch("/api/digest", { method: "POST" });
      if (!res.ok) {
        const json = (await res.json().catch(() => null)) as { error?: { message?: string } } | null;
        throw new Error(json?.error?.message ?? "Couldn't generate the digest.");
      }
      await readTextStream(res, setText, (m) => setMeta(m as Meta));
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setPending(false);
    }
  }

  return (
    <section className="rounded-xl border bg-card p-5" aria-labelledby="digest-heading">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h2 id="digest-heading" className="flex items-center gap-2 font-medium">
          <Sparkles className="size-4 text-brand-clay" aria-hidden /> AI summary
        </h2>
        {aiAvailable ? (
          <Button onClick={generate} disabled={pending} aria-busy={pending}>
            {pending ? <Spinner label="Writing" /> : null}
            {text ? "Regenerate" : "Write this week's digest"}
          </Button>
        ) : (
          <AiUnavailable />
        )}
      </div>
      <div aria-live="polite" className="mt-4">
        {error ? <p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p> : null}
        {text ? <div className="text-sm leading-relaxed whitespace-pre-wrap">{plain(text)}</div> : null}
        {!text && !error ? (
          <p className="text-sm text-muted-foreground">
            {aiAvailable ? "The model writes a short narrative from the numbers on this page. It only sees these stats — never customer names or notes." : "Configure an AI provider to get a written summary. The numbers above are always available."}
          </p>
        ) : null}
        {meta ? (
          meta.unverified.length ? (
            <p className="mt-4 flex items-start gap-2 rounded-md bg-amber-500/10 p-3 text-sm text-amber-800 dark:text-amber-200">
              <AlertTriangle className="mt-0.5 size-4 shrink-0" aria-hidden />
              <span>
                Check these numbers — they don&apos;t appear in the stats: <strong>{meta.unverified.join(", ")}</strong>
              </span>
            </p>
          ) : (
            <p className="mt-4 text-xs text-muted-foreground">Every number in this summary matches the stats above.</p>
          )
        ) : null}
        {meta ? (
          <p className="mt-2 text-[11px] text-muted-foreground">
            AI-generated by {meta.provider} · {meta.model}.
          </p>
        ) : null}
      </div>
    </section>
  );
}
